-- Create USERS table
CREATE TABLE USERS (
    USER_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    ROLE VARCHAR(20) DEFAULT 'CUSTOMER', -- 'CUSTOMER' or 'ADMIN'
    BALANCE DECIMAL(10, 2) DEFAULT 0.00,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create ADDRESSES table
CREATE TABLE ADDRESSES (
    ADDRESS_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    USER_ID INT,
    FULL_NAME VARCHAR(100),
    ADDRESS_LINE VARCHAR(255),
    CITY VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Create CATEGORIES table
CREATE TABLE CATEGORIES (
    CATEGORY_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CATEGORY_NAME VARCHAR(100) NOT NULL UNIQUE
);

-- Create PRODUCTS table
CREATE TABLE PRODUCTS (
    PRODUCT_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CATEGORY_ID INT,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRICE DECIMAL(10, 2) NOT NULL,
    STOCK_QUANTITY INT,
    TYPE VARCHAR(20), -- 'PHYSICAL' or 'DIGITAL'
    WEIGHT DECIMAL(5, 2), -- For Physical Products
    DOWNLOAD_LINK VARCHAR(255), -- For Digital Products
    IMAGE_PATH VARCHAR(255),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
);

-- Create SHOPPING_CART table
CREATE TABLE SHOPPING_CART (
    CART_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    USER_ID INT,
    PRODUCT_ID INT,
    QUANTITY INT DEFAULT 1,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

-- Create ORDERS table
CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    USER_ID INT,
    TOTAL_AMOUNT DECIMAL(10, 2),
    STATUS VARCHAR(20), -- 'PENDING', 'PAID', 'SHIPPED'
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Create ORDER_ITEMS table
CREATE TABLE ORDER_ITEMS (
    ITEM_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ORDER_ID INT,
    PRODUCT_ID INT,
    QUANTITY INT,
    PRICE_AT_PURCHASE DECIMAL(10, 2),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

-- Create PAYMENTS table
CREATE TABLE PAYMENTS (
    PAYMENT_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ORDER_ID INT,
    PAYMENT_METHOD VARCHAR(50),
    AMOUNT DECIMAL(10, 2),
    STATUS VARCHAR(20),
    PAYMENT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

-- Create WISHLIST table
CREATE TABLE WISHLIST (
    WISHLIST_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    USER_ID INT,
    PRODUCT_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

-- Create PAYMENT_METHODS table
CREATE TABLE PAYMENT_METHODS (
    PAYMENT_METHOD_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    USER_ID INT,
    CARD_NUMBER VARCHAR(20),
    EXPIRY_DATE VARCHAR(10),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Seed Data: Categories
INSERT INTO CATEGORIES (CATEGORY_NAME) VALUES ('Electronics');
INSERT INTO CATEGORIES (CATEGORY_NAME) VALUES ('Books');
INSERT INTO CATEGORIES (CATEGORY_NAME) VALUES ('Clothing');

-- Seed Data: Users
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, ROLE, BALANCE) VALUES ('admin', 'admin123', 'admin@store.com', 'ADMIN', 1000.00);
INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, ROLE, BALANCE) VALUES ('user', 'user123', 'user@store.com', 'CUSTOMER', 50.00);

-- Seed Data: Physical Products
INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, TYPE, WEIGHT, CATEGORY_ID) 
VALUES ('Java Programming Book', 'Comprehensive guide to Java 21', 59.99, 10, 'PHYSICAL', 1.5, 2);

INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, TYPE, WEIGHT, CATEGORY_ID) 
VALUES ('Mechanical Keyboard', 'Clicky keys for coding', 120.50, 5, 'PHYSICAL', 0.8, 1);

-- Seed Data: Digital Products
INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, TYPE, DOWNLOAD_LINK, CATEGORY_ID) 
VALUES ('IntelliJ IDEA License', '1-year subscription', 149.00, 999, 'DIGITAL', 'https://jetbrains.com/download', 1);

INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE, STOCK_QUANTITY, TYPE, DOWNLOAD_LINK, CATEGORY_ID) 
VALUES ('Design Patterns E-Book', 'PDF version of GoF book', 29.99, 999, 'DIGITAL', 'https://ebooks.com/gof.pdf', 2);
